import { DescriptionsProps } from "antd";
import { Team } from "../Services/Team";

export const getImage = (team: Team) => {
  const city = team.city.toLowerCase().replace(" ", "-");
  const name = team.name.toLowerCase();
  const imageName = `${city}-${name}`;
  if (team.urlImage) return team.urlImage;
  return `https://loodibee.com/wp-content/uploads/nfl-${imageName}-team-logo-2-350x350.png`;
};

export const getAllTeams = () => {
  const valueRandom = 9000000000000;
  const allTeams: Array<Team> = [
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Arizona",
      name: "Cardinals",
      abr: "ARI",
      conf: "NFC",
      div: "West",
      cPrim: "#97233F",
      cSecn: "#FFB612",
      superBowlChamps: [],
      stadium: "State Farm Stadium",
      capacityStadium: "63,400",
      cityStadium: "Glendale, Arizona",
      establishedYear: "1920",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Atlanta",
      name: "Falcons",
      abr: "ATL",
      conf: "NFC",
      div: "South",
      cPrim: "#A71930",
      cSecn: "#000000",
      superBowlChamps: [],
      stadium: "Mercedes-Benz Stadium",
      capacityStadium: "71,000",
      cityStadium: "Atlanta, Georgia",
      establishedYear: "1966",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Baltimore",
      name: "Ravens",
      abr: "BAL",
      conf: "AFC",
      div: "North",
      cPrim: "#241773",
      cSecn: "#9E7C0C",
      superBowlChamps: ["2000", "2012"],
      stadium: "M&T Bank Stadium",
      capacityStadium: "71,008",
      cityStadium: "Baltimore, Maryland",
      establishedYear: "1996	",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Buffalo",
      name: "Bills",
      abr: "BUF",
      conf: "AFC",
      div: "East",
      cPrim: "#00338D",
      cSecn: "#C60C30",
      superBowlChamps: [],
      stadium: "Highmark Stadium",
      capacityStadium: "71,608",
      cityStadium: "Orchard Park, New York",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Carolina",
      name: "Panthers",
      abr: "CAR",
      conf: "NFC",
      div: "South",
      cPrim: "#0085CA",
      cSecn: "#101820",
      superBowlChamps: [],
      stadium: "Bank of America Stadium",
      capacityStadium: "74,867",
      cityStadium: "Charlotte, North Carolina",
      establishedYear: "1995	",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Chicago",
      name: "Bears",
      abr: "CHI",
      conf: "NFC",
      div: "North",
      cPrim: "#0B162A",
      cSecn: "#C83803",
      superBowlChamps: ["1985"],
      stadium: "Soldier Field",
      capacityStadium: "61,500",
      cityStadium: "Chicago, Illinois",
      establishedYear: "1920",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Cincinnati",
      name: "Bengals",
      abr: "CIN",
      conf: "AFC",
      div: "North",
      cPrim: "#FB4F14",
      cSecn: "#000000",
      superBowlChamps: [],
      stadium: "Paycor Stadium",
      capacityStadium: "65,515",
      cityStadium: "Cincinnati, Ohio",
      establishedYear: "1968",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Cleveland",
      name: "Browns",
      abr: "CLE",
      conf: "AFC",
      div: "North",
      cPrim: "#FF3C00",
      cSecn: "#311D00",
      superBowlChamps: [],
      stadium: "Cleveland Browns Stadium",
      capacityStadium: "67,431",
      cityStadium: "Cleveland, Ohio",
      establishedYear: "1946",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Dallas",
      name: "Cowboys",
      abr: "DAL",
      conf: "NFC",
      div: "East",
      cPrim: "#041E42",
      cSecn: "#869397",
      superBowlChamps: ["1971", "1977", "1992", "1993", "1995"],
      stadium: "AT&T Stadium",
      capacityStadium: "80,000",
      cityStadium: "Arlington, Texas",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Denver",
      name: "Broncos",
      abr: "DEN",
      conf: "AFC",
      div: "West",
      cPrim: "#002244",
      cSecn: "#FB4F14",
      superBowlChamps: ["1997", "1998", "2015"],
      stadium: "Empower Field at Mile High",
      capacityStadium: "76,125",
      cityStadium: "Denver, Colorado",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Detroit",
      name: "Lions",
      abr: "DET",
      conf: "NFC",
      div: "North",
      cPrim: "#0076B6",
      cSecn: "#B0B7BC",
      superBowlChamps: [],
      stadium: "Ford Field",
      capacityStadium: "65,000",
      cityStadium: "Detroit, Michigan",
      establishedYear: "1930",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Green Bay",
      name: "Packers",
      abr: "GB",
      conf: "NFC",
      div: "North",
      cPrim: "#203731",
      cSecn: "#FFB612",
      superBowlChamps: ["1966", "1967", "1996", "2010"],
      stadium: "Lambeau Field",
      capacityStadium: "81,441",
      cityStadium: "Green Bay, Wisconsin",
      establishedYear: "1921",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Houston",
      name: "Texans",
      abr: "HOU",
      conf: "AFC",
      div: "South",
      cPrim: "#03202F",
      cSecn: "#A71930",
      superBowlChamps: [],
      stadium: "NRG Stadium",
      capacityStadium: "72,220",
      cityStadium: "Houston, Texas",
      establishedYear: "2002",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Indianapolis",
      name: "Colts",
      abr: "IND",
      conf: "AFC",
      div: "South",
      cPrim: "#002C5F",
      cSecn: "#A2AAAD",
      superBowlChamps: ["1970", "2006"],
      stadium: "Lucas Oil Stadium",
      capacityStadium: "63,000",
      cityStadium: "Indianapolis, Indiana",
      establishedYear: "1953",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Jacksonville",
      name: "Jaguars",
      abr: "JAC",
      conf: "AFC",
      div: "South",
      cPrim: "#006778",
      cSecn: "#9F792C",
      superBowlChamps: [],
      stadium: "EverBank Stadium",
      capacityStadium: "67,838",
      cityStadium: "Jacksonville, Florida",
      establishedYear: "1995",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Kansas City",
      name: "Chiefs",
      abr: "KC",
      conf: "AFC",
      div: "West",
      cPrim: "#E31837",
      cSecn: "#FFB81C",
      superBowlChamps: ["1969", "2019", "2022"],
      stadium: "Arrowhead Stadium",
      capacityStadium: "76,416",
      cityStadium: "Kansas City, Missouri",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Las Vegas",
      name: "Raiders",
      abr: "LV",
      conf: "AFC",
      div: "West",
      cPrim: "#000000",
      cSecn: "#A5ACAF",
      superBowlChamps: ["1976", "1980", "1983"],
      stadium: "Allegiant Stadium",
      capacityStadium: "65,000",
      cityStadium: "65,000",
      establishedYear: "1960",
      urlImage:
        "https://loodibee.com/wp-content/uploads/nfl-oakland-raiders-team-logo-350x350.png",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Los Angeles",
      name: "Chargers",
      abr: "LAC",
      conf: "AFC",
      div: "West",
      cPrim: "#002A5E",
      cSecn: "#FFC20E",
      superBowlChamps: [],
      stadium: "SoFi Stadium",
      capacityStadium: "70,000",
      cityStadium: "Inglewood, California",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Los Angeles",
      name: "Rams",
      abr: "LAR",
      conf: "NFC",
      div: "West",
      cPrim: "#003594",
      cSecn: "#FFA300",
      superBowlChamps: ["1999", "2021"],
      stadium: "SoFi Stadium",
      capacityStadium: "70,000",
      cityStadium: "Inglewood, California",
      establishedYear: "1937",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Miami",
      name: "Dolphins",
      abr: "MIA",
      conf: "AFC",
      div: "East",
      cPrim: "#008E97",
      cSecn: "#FC4C02",
      superBowlChamps: ["1972", "1973"],
      stadium: "Hard Rock Stadium",
      capacityStadium: "65,326",
      cityStadium: "Miami Gardens, Florida",
      establishedYear: "1966",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Minnesota",
      name: "Vikings",
      abr: "MIN",
      conf: "NFC",
      div: "North",
      cPrim: "#4F2683",
      cSecn: "#FFC62F",
      superBowlChamps: [],
      stadium: "U.S. Bank Stadium",
      capacityStadium: "66,655",
      cityStadium: "Minneapolis, Minnesota",
      establishedYear: "1961",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "New England",
      name: "Patriots",
      abr: "NE",
      conf: "AFC",
      div: "East",
      cPrim: "#002244",
      cSecn: "#C60C30",
      superBowlChamps: ["2001", "2003", "2004", "2014", "2016", "2018"],
      stadium: "Gillette Stadium",
      capacityStadium: "66,829",
      cityStadium: "Foxborough, Massachusetts",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "New Orleans",
      name: "Saints",
      abr: "NO",
      conf: "NFC",
      div: "South",
      cPrim: "#D3BC8D",
      cSecn: "#101820",
      superBowlChamps: ["2009"],
      stadium: "Caesars Superdome",
      capacityStadium: "73,208",
      cityStadium: "New Orleans, Louisiana",
      establishedYear: "1967",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "New York",
      name: "Giants",
      abr: "NYG",
      conf: "NFC",
      div: "East",
      cPrim: "#0B2265",
      cSecn: "#A71930",
      superBowlChamps: ["1986", "1990", "2007", "2011"],
      stadium: "MetLife Stadium",
      capacityStadium: "82,500",
      cityStadium: "East Rutherford, New Jersey",
      establishedYear: "1925",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "New York",
      name: "Jets",
      urlImage:
        "https://loodibee.com/wp-content/uploads/nfl-new-york-jets-team-logo-350x350.png",
      abr: "NYJ",
      conf: "AFC",
      div: "East",
      cPrim: "#125740",
      cSecn: "#000000",
      superBowlChamps: ["1968"],
      stadium: "MetLife Stadium",
      capacityStadium: "82,500",
      cityStadium: "East Rutherford, New Jersey",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Philadelphia",
      name: "Eagles",
      abr: "PHI",
      conf: "NFC",
      div: "East",
      cPrim: "#004C54",
      cSecn: "#A5ACAF",
      superBowlChamps: ["2017"],
      stadium: "Lincoln Financial Field",
      capacityStadium: "69,596",
      cityStadium: "Philadelphia, Pennsylvania",
      establishedYear: "1933",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Pittsburgh",
      name: "Steelers",
      abr: "PIT",
      conf: "AFC",
      div: "North",
      cPrim: "#101820",
      cSecn: "#FFB612",
      superBowlChamps: ["1974", "1975", "1978", "1979", "2005", "2008"],
      stadium: "Acrisure Stadium",
      capacityStadium: "68,400",
      cityStadium: "Pittsburgh, Pennsylvania",
      establishedYear: "1933",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "San Francisco",
      name: "49ers",
      abr: "SF",
      conf: "NFC",
      div: "West",
      cPrim: "#AA0000",
      cSecn: "#B3995D",
      superBowlChamps: ["1981", "1984", "1988", "1989", "1994"],
      stadium: "Levi's Stadium",
      capacityStadium: "68,500",
      cityStadium: "Santa Clara, California",
      establishedYear: "1946",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Seattle",
      name: "Seahawks",
      abr: "SEA",
      conf: "NFC",
      div: "West",
      cPrim: "#002244",
      cSecn: "#69BE28",
      superBowlChamps: ["2013"],
      stadium: "Lumen Field",
      capacityStadium: "69,000",
      cityStadium: "Seattle, Washington",
      establishedYear: "1976",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Tampa Bay",
      name: "Buccaneers",
      abr: "TB",
      conf: "NFC",
      div: "South",
      cPrim: "#D50A0A",
      cSecn: "#B1BABF",
      superBowlChamps: ["2002", "2020"],
      stadium: "Raymond James Stadium",
      capacityStadium: "69,218",
      cityStadium: "Tampa, Florida",
      establishedYear: "1976",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Tennessee",
      name: "Titans",
      abr: "TEN",
      conf: "AFC",
      div: "South",
      cPrim: "#4B92DB",
      cSecn: "#C8102E",
      superBowlChamps: [],
      stadium: "Nissan Stadium",
      capacityStadium: "69,143",
      cityStadium: "Nashville, Tennessee",
      establishedYear: "1960",
    },
    {
      id: Math.floor(Math.random() * valueRandom) + 1,
      city: "Washington",
      name: "Commanders",
      abr: "WAS",
      conf: "NFC",
      div: "East",
      cPrim: "#773141",
      cSecn: "#FFB612",
      superBowlChamps: ["1982", "1987", "1991"],
      stadium: "FedExField",
      capacityStadium: "58,000",
      cityStadium: "Landover, Maryland",
      establishedYear: "1932",
      urlImage:
        "https://loodibee.com/wp-content/uploads/washington-commanders-logo-350x350.png",
    },
  ];

  return allTeams.sort((a, b) => a.id - b.id);
};

export const getDetailsTeam = (team?: Team) => {
  const items: DescriptionsProps["items"] = [
    {
      label: "Name",
      span: { xl: 2, xxl: 2 },
      children: `${team?.city} ${team?.name}`,
    },
    {
      label: "City",
      span: { xl: 2, xxl: 2 },
      children: team?.cityStadium,
    },
    {
      label: "Abrev",
      span: { xl: 2, xxl: 2 },
      children: team?.abr,
    },
    {
      label: "Established",
      span: { xl: 2, xxl: 2 },
      children: team?.establishedYear,
    },
    {
      label: "Stadium",
      span: { xs: 1, sm: 2, md: 3, lg: 3, xl: 2, xxl: 2 },
      children: team?.stadium,
    },
    {
      label: "Capacity",
      span: { xs: 1, sm: 2, md: 3, lg: 3, xl: 2, xxl: 2 },
      children: team?.capacityStadium,
    },
    {
      label: "Super Bowls",
      span: { xs: 1 },
      children: team?.superBowlChamps.join(", "),
    },
  ];
  return items;
};
